In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [28]:
data = open("./in/phosphorylation_results.txt")

In [29]:
store_phospho = dict()
for line in data:
    if "# human" in line:
        lobj = [x for x in line.strip().split(" ") if x != ""]
        if lobj[6]=="unsp":
            continue 

        try:
            store_phospho[lobj[6]] 
        except:
            store_phospho[lobj[6]] = dict()

        store_phospho[lobj[6]][int(lobj[2])] = float(lobj[5])

In [30]:
df = pd.DataFrame(store_phospho)
df

,GSK3,CaM-II,cdc2,CKI,DNAPK,p38MAPK,CKII,PKG,ATM,PKA,RSK,cdk5,PKB,PKC,EGFR,INSR,SRC
14,0.448,0.434,0.397,0.363,0.337,0.325,0.317,0.303,0.295,0.210,0.183,0.178,0.093,0.071,NaN,NaN,NaN
24,0.453,0.468,0.449,0.372,0.348,0.303,0.534,0.248,0.266,0.252,0.285,0.158,0.084,0.156,NaN,NaN,NaN
26,0.458,0.397,0.402,0.386,0.380,0.265,0.620,0.341,0.292,0.120,0.289,0.137,0.080,0.176,NaN,NaN,NaN
27,0.427,0.437,0.427,0.422,0.351,0.316,0.423,0.210,0.283,0.095,0.458,0.165,0.091,0.231,NaN,NaN,NaN
42,0.442,0.464,0.456,0.362,0.341,0.415,0.349,0.325,0.257,0.138,0.224,0.246,0.082,0.155,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.338,0.455,0.500
181,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.351,0.429,0.481
202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.417,0.416,0.499
225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.493,0.565,0.418
246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.335,0.430,0.328

In [31]:
df_filled = df.fillna(0)

In [32]:
annot = df_filled.applymap(lambda x: "*" if pd.notnull(x) and x > 0.8 else "")
annot

/tmp/ipykernel_3538328/1325047644.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  annot = df_filled.applymap(lambda x: "*" if pd.notnull(x) and x > 0.8 else "")

,GSK3,CaM-II,cdc2,CKI,DNAPK,p38MAPK,CKII,PKG,ATM,PKA,RSK,cdk5,PKB,PKC,EGFR,INSR,SRC
14,,,,,,,,,,,,,,,,,
24,,,,,,,,,,,,,,,,,
26,,,,,,,,,,,,,,,,,
27,,,,,,,,,,,,,,,,,
42,,,,,,,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,,,,,,,,,,,,,,,,,
181,,,,,,,,,,,,,,,,,
202,,,,,,,,,,,,,,,,,
225,,,,,,,,,,,,,,,,,
246,,,,,,,,,,,,,,,,,

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.colors import ListedColormap, BoundaryNorm, LinearSegmentedColormap

df_sorted = df_filled.sort_index()
df_sorted = df_sorted.sort_index(axis=1)

annot = df_sorted.applymap(lambda x: "*" if x > 0.8 else "")
colors = [(1, 1, 1)] + sns.color_palette("BuPu", 256).as_hex()  
cmap = ListedColormap(colors)
norm = plt.Normalize(vmin=0.5, vmax=1.0)

plt.figure(figsize=(10, 20))
ax = sns.heatmap(df_sorted, 
                 annot=annot,
                 fmt="", 
                 linewidths=0,
                 linecolor=None,
                 cmap=cmap,
                 norm=norm,
                 cbar_kws={"label": "Phosphorylation Score"},
                 square=False)

ax.set_xlabel("Kinase", fontsize=32)
ax.set_ylabel("Residue Position", fontsize=32)
ax.set_title("", fontsize=28, fontweight='bold')
plt.xticks(rotation=45, ha='right', fontsize=20)
plt.yticks(rotation=0, fontsize=20)
plt.tight_layout()

plt.savefig("phosphorylation_heatmap_full.png", dpi=300, bbox_inches='tight')
plt.close()